"""Passenger domain model (requirements.md 5.4, 16.1)."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class PassengerStatus(str, Enum):
    GENERATED = "GENERATED"
    WAITING = "WAITING"
    ASSIGNED = "ASSIGNED"
    ONBOARD = "ONBOARD"
    ARRIVED = "ARRIVED"
    LEFT_BEHIND = "LEFT_BEHIND"


class Direction(int, Enum):
    UP = 1
    DOWN = -1
    IDLE = 0


@dataclass
class Passenger:
    passenger_id: str
    hall_arrival_time: float
    origin_floor: int
    destination_floor: int
    group_id: str | None = None
    group_size: int = 1
    luggage_factor: float = 1.0

    generated_at: float | None = None
    call_time: float | None = None
    assigned_car_id: str | None = None
    board_time: float | None = None
    arrival_time: float | None = None
    status: PassengerStatus = PassengerStatus.GENERATED

    # Optional 2D walk that precedes the hall arrival, as a sequence of
    # (grid_id, timestamp) pairs (requirements.md 9.6). Only populated when
    # generated by TrajectoryTrafficGenerator; None for Poisson/hotel arrivals.
    trajectory: list[tuple[int, float]] | None = None

    @property
    def direction(self) -> Direction:
        if self.destination_floor > self.origin_floor:
            return Direction.UP
        if self.destination_floor < self.origin_floor:
            return Direction.DOWN
        return Direction.IDLE

    @property
    def occupancy(self) -> float:
        """Capacity units consumed, including luggage."""
        return self.group_size * self.luggage_factor

    @property
    def waiting_time(self) -> float | None:
        if self.board_time is None:
            return None
        return self.board_time - self.hall_arrival_time

    @property
    def ride_time(self) -> float | None:
        if self.board_time is None or self.arrival_time is None:
            return None
        return self.arrival_time - self.board_time

    @property
    def total_service_time(self) -> float | None:
        if self.arrival_time is None:
            return None
        return self.arrival_time - self.hall_arrival_time
